name = "minilog"
main = "src/index.ts"
compatibility_date = "2023-09-04"

# KV Namespace para almacenar logs
kv_namespaces = [
  { binding = "MINILOG_KV", id = "24a91131165944d3812d81da12086fa8", preview_id = "c7a007c7a575471eb4d97554bc1cfd16" }
]

[vars]
# Variables de entorno
# Reemplaza estos valores con tus propias API keys y secretos
JWT_SECRET = "reemplazar-con-tu-secreto-real"

# Rutas
routes = [
  { pattern = "api.minilog.workers.dev", custom_domain = true }
]

# Configuración de límites y capacidades
#[limits]
#cpu_ms = 10

# Configuración de dev
[dev]
port = 8787 